version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3"
python:
  install:
    - requirements: docs/requirements.txt
    - path: .
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true